const BlogPostData = [
    {
        id: 1,
        category: "lifestyle",
        title: "10 Minimalist Habits for a More Focused Life",
        content: "Minimalism helps eliminate distractions and improve focus. From decluttering your home to practicing digital minimalism, these habits can enhance clarity and productivity in your daily routine.",
        author: "Sarah Thompson",
        date: "03-01-2025",
        image: "/images/blog/7.jpg",
    },
    {
        id: 2,
        category: "sports",
        title: "Top 5 Workouts to Boost Your Energy",
        content: "Boost your energy levels with these 5 effective workouts. From HIIT to yoga, discover exercises that increase stamina, improve mood, and enhance your overall health.",
        author: "David Miller",
        date: "15-02-2025",
        image: "/images/blog/8.jpg",
    },
    {
        id: 3,
        category: "science",
        title: "The Future of Space Travel in 2030",
        content: "By 2030, space travel may become more accessible than ever. With advancements in reusable rockets and interplanetary exploration, we’re entering a new era of cosmic discovery.",
        author: "Emily Carter",
        date: "27-03-2025",
        image: "/images/blog/9.jpg",
    },
    {
        id: 4,
        category: "news",
        title: "Global Market Trends You Should Know",
        content: "Economic growth, emerging markets, and technological disruptions are shaping global financial trends. Stay informed to make better business and investment decisions.",
        author: "Michael Johnson",
        date: "09-04-2025",
        image: "/images/blog/10.jpg",
    },
    {
        id: 5,
        category: "recipe",
        title: "5 Quick & Healthy Breakfast Ideas",
        content: "Start your day with these healthy and quick breakfast recipes. From smoothie bowls to overnight oats, fuel your mornings without spending hours in the kitchen.",
        author: "Olivia Brown",
        date: "22-05-2025",
        image: "/images/blog/11.jpg",
    },
    {
        id: 6,
        category: "lifestyle",
        title: "How to Build a Morning Routine That Sticks",
        content: "A consistent morning routine sets the tone for the rest of your day. Learn how to create habits that last, including meditation, exercise, and intentional planning.",
        author: "James Lee",
        date: "10-06-2025",
        image: "/images/blog/12.jpg",
    },
];

export default BlogPostData;
