export const posts = [
    {
        id: 1,
        category: "Finance & Sports",
        title: "How to manage retirement savings with high interest rates",
        paragraph: "With interest rates holding steady, financial advisors recommend diversifying investments to secure a stable retirement.",
        author: "Sarah Thompson",
        date: "June 1, 2024",
        imageUrl: "/images/blog1.jpeg",
    },
    {
        id: 2,
        category: "Healthcare Insights",
        title: "Teachers, Nurses, and Care Workers Are Reaching a Breaking Point",
        paragraph: "Essential workers are facing burnout as they continue to shoulder the weight of an overstressed system with little support.",
        author: "Daniel Kim",
        date: "June 3, 2024",
        imageUrl: "/images/blog2.jpeg",
    },
    {
        id: 3,
        category: "Climate & Industry",
        title: "Just 57 Firms Responsible for 80% of Global Carbon Emissions",
        paragraph: "A new report reveals that a small number of companies are contributing the majority of global carbon dioxide output.",
        author: "Ayesha Rahman",
        date: "June 2, 2024",
        imageUrl: "/images/blog3.jpeg",
    },
    {
        id: 4,
        category: "Economic Strategy",
        title: "Smart Strategies to Save for Retirement in Today’s Market",
        paragraph: "From IRAs to high-yield savings, experts suggest combining traditional and modern tactics for long-term financial growth.",
        author: "Michael Lee",
        date: "June 4, 2024",
        imageUrl: "/images/blog4.jpeg",
    },
    {
        id: 5,
        category: "Economic Strategy",
        title: "10 Things To Do In The Evening Instead Of Watching Netflix",
        paragraph: "Now, you don't need to throw your TV out the window and force yourself into some complicated evening routine.",
        author: "Michael Lee",
        date: "June 4, 2024",
        imageUrl: "/images/blog5.webp",
    },
    {
        id: 6,
        category: "Science",
        title: "ChatGPT Is Poisoning Your Brain.Here‘s How to Stop It Before It’s Too Late.",
        paragraph: "Maybe I’m being a little dramatic here. However, even on a small scale, this feedback loop can be problematic, especially if you’re like me and use LLMs daily.",
        author: "Ibrahim Gazi",
        date: "April 4, 2025",
        imageUrl: "/images/blog6.webp",
    },
    {
        id: 7,
        category: "Life Style",
        title: "10 Ways To Reduce Motion Sickness When Using VR",
        paragraph: "Maybe I’m being a little dramatic here. However, even on a small scale, this feedback loop can be problematic, especially if you’re like me and use LLMs daily.",
        author: "Jordan Gibbs",
        date: "April 4, 2025",
        imageUrl: "/images/blog7.jpeg",
    },
    {
        id: 8,
        category: "My Life",
        title: "30 Days. 1 Rule. Total Focus.That Rewired My Focus and Changed My Life.",
        paragraph: "Maybe I’m being a little dramatic here. However, even on a small scale, this feedback loop can be problematic, especially if you’re like me and use LLMs daily.",
        author: "Shubham Kumbhar",
        date: "April 4, 2025",
        imageUrl: "/images/blog8.webp",
    },
    {
        id: 9,
        category: "My Life",
        title: "A simple 3-step process to improve your ability to focus and increase your attention span.",
        paragraph: "Maybe I’m being a little dramatic here. However, even on a small scale, this feedback loop can be problematic, especially if you’re like me and use LLMs daily.",
        author: "Abbas Ali",
        date: "Mar 30, 2025",
        imageUrl: "/images/blog9.jpg",
    },
    {
        id: 10,
        category: "My Life",
        title: "30 Days. 1 Rule. Total Focus.That Rewired My Focus and Changed My Life.",
        paragraph: "Maybe I’m being a little dramatic here. However, even on a small scale, this feedback loop can be problematic, especially if you’re like me and use LLMs daily.",
        author: "Shubham Kumbhar",
        date: "April 4, 2025",
        imageUrl: "/images/blog8.webp",
    },
    {
        id: 11,
        category: "My Life",
        title: "30 Days. 1 Rule. Total Focus.That Rewired My Focus and Changed My Life.",
        paragraph: "Maybe I’m being a little dramatic here. However, even on a small scale, this feedback loop can be problematic, especially if you’re like me and use LLMs daily.",
        author: "Shubham Kumbhar",
        date: "April 4, 2025",
        imageUrl: "/images/blog8.webp",
    },

];

export default posts;
