import "./globals.css";
import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthInitializer from '@/components/Auth/AuthInitializer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ibra Blogs",
  description: "Generated by Ibrahim - The Coder",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} relative min-h-screen`}>
        <div className="svg-bg" />
        <div className="relative z-10">
         <AuthInitializer />
         {children}
         <Toaster position="top-center" richColors />
        </div>
      </body>
    </html>
  );
}